### ISSUE TITLE
Double-quoted string gets interpreted as variable

### ISSUE THREAD

**Issue by bardo** [exiang/php-font-awesome-to-png#3]
In generateIconData.php, line 13, there is a call to `if(strstr($l, "$fa-var-"))` failing because PHP looks for the `$fa` variable. As a result `icons.data.php` is broken and `generate.php` produces empty files.

Fixing is just a matter of using single quotes.

**Comment by exiang** [comment]
Hi Corrado Primier,

Noted with thanks. Bug fixed and changes committed.

On Wednesday, October 15, 2014 12:36 AM, Corrado Primier notifications@github.com wrote:

In generateIconData.php, line 13, there is a call to if(strstr($l, "$fa-var-")) failing because PHP looks for the $fa variable. As a result icons.data.php is broken and generate.php produces empty files.
Fixing is just a matter of using single quotes.

**Comment by bardo** [comment]
Perfect, thanks!
